공간일기 작업
yeogiya/yeogiya-backend pull request #16
Opened 2023-10-24 04:28 UTC by ijnooyah

- 공간일기 쓰기, 수정,  삭제, 뷰, 달력(리스트) 작업 완료
- PrincipalDetails 클래스 추가해 @AuthenticationPrincipal 어노테이션만으로 로그인정보 불러올 수 있게함

2023-10-26 05:57 UTC, geniushyeon requested changes

2023-10-26 05:57 UTC, geniushyeon commented on yeogiya-common/src/main/java/com/yeogiya/entity/diary/DiaryImage.java
> +    @Column(name = "org_name")
원래 단어가 original_name 인가요? 그렇게 길지 않아서 줄이기 전 이름으로 쓰는 게 더 알아보기 쉬워서 좋을 것 같아요.

2023-10-26 05:57 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/controller/DiaryController.java
> +        if (principal != null) {
이건 컨트롤러 단에서 체크하는 게 아니라 더 앞에서(필터, 인터셉터 등) 체크해야 할 것 같네요.

2023-10-26 05:57 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/dto/response/DiariesResponseDTO.java
> +        for(DiaryHashtag diaryHashtag : diaryHashtags) {
stream을 사용한 코드로 개선할 수 있을 거 같습니다!

2023-10-26 05:57 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/dto/response/DiariesResponseDTO.java
> +        List<String> diaryImagePaths = new ArrayList<>();
여기도 스트림으로 개선할 수 있을 거 같아요~

2023-10-26 05:57 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +        diary.setMember(member);
setter 말고 다른 방법으로 할 수는 없을까요?

2023-10-26 05:57 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +public class DiaryService {
이 서비스 내의 각 메소드들이 전부 너무 많은 역할을 수행하고 있는 것 같습니다.

2023-10-26 05:57 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/util/DateUtils.java
> +public class DateUtils {
이 클래스가 util성 클래스면 메소드들은 static 메소드로 선언하는 게 어떨까요?

2023-10-26 05:58 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/controller/DiaryController.java
> +        if (principal != null) {
어떤거 말이죠? principal이 null이아니라면 작동하는 로직 말하시는건가용???

2023-10-26 05:59 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/controller/DiaryController.java
> +        if (principal != null) {
@ijnooyah 로그인 안 되어있을 때 예외처리하는 로직이요!

2023-10-26 06:00 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/controller/DiaryController.java
> +        if (principal != null) {
@geniushyeon 넵 알겠습니다~

2023-10-26 06:00 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +public class DiaryService {
@geniushyeon 이부분은 어떤식으로 수행되면 좋은건가요?

2023-10-26 06:02 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +public class DiaryService {
@ijnooyah 보통 저는 서비스에서는 그 서비스와 관련된 레포지토리만 참조하고 (DiaryService 같은 경우에는 DiaryRepository겠죠) 서비스에서 서비스를 참조하는 구조로 가져가는 편입니다.

2023-10-26 06:03 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +public class DiaryService {
@geniushyeon 아하 이해했습니다 한번 수정해볼게요!

2023-10-31 13:41 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/dto/response/DiariesResponseDTO.java
> +        for(DiaryHashtag diaryHashtag : diaryHashtags) {
@geniushyeon  지현님 stream을 이용한 코드가 너무 많아 그런데 어떤식으로 개선할수있는거죠?

2023-10-31 13:43 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +        diary.setMember(member);
@geniushyeon 세터말고는 다른 방법이 생각이 잘안나는데요 혹시 뭐 생각나는게 있으신건가요

2023-10-31 13:44 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +public class DiaryService {
@geniushyeon 이부분도 계속 고민해봤는데요 ㅜ ㅜ 서비스단으로 각각 어떻게 떼어내야할지를 모르겠네요 ㅠㅠ

2023-10-31 13:45 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/util/DateUtils.java
> +public class DateUtils {
@geniushyeon 이유를 알수있을까요?

2023-11-01 03:08 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/dto/response/DiariesResponseDTO.java
> +        for(DiaryHashtag diaryHashtag : diaryHashtags) {
@ijnooyah 
```java
this.hashtags = diary.getDiaryHashtags().stream()
                .map(DiaryHashtag::getHashtag)
                .map(Hashtag::getName)
                .collect(Collectors.toList());
```

이런 식으로 쓸 수 있지 않을까요~

2023-11-01 03:11 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +        diary.setMember(member);
```java
Diary diary = new Diary(diarySaveRequestDTO.getContent(), diarySaveRequestDTO.getOpenYn());
```

저라면 여기에서 생성자의 매개변수로 넣어줄 거 같아요.

2023-11-01 03:13 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +        diary.setMember(member);
@geniushyeon 오호 저도 이생각한번 해봤는데 괜찮은 방법인지 자신이 없었는데 감사합니다! 적용시키겠습니다.

2023-11-01 03:14 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +        diary.setMember(member);
@ijnooyah 추가로 조언드리면, `diarySaveRequestDTO` 객체가 Diary 객체 생성에 필요한 정보를 알고 있기 때문에 Diary 생성 로직은 DTO 내부로 이동시켜주는 게 좋습니다.

2023-11-01 03:21 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/diary/service/DiaryService.java
> +        diary.setMember(member);
@geniushyeon 지현님 죄송한데 제가 지식이 부족해서 설명자체를 못알아들었어요 ㅠㅠ 혹시 간단한 예시들어주실수 있을까요?? 감이 전혀안잡혀서요

2023-11-01 03:22 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/util/DateUtils.java
> +public class DateUtils {
@ijnooyah static 메소드는 객체 생성 없이도 접근할 수 있으니 여러 곳에서 쉽게 호출하고 사용하기 쉬워지겠죠?
추가로, CalendarPageRequestDTO를 매개변수로 하는 메소드들이 있는데 유틸성 함수는 재사용되는 곳이 많으니까 아래처럼 기본적인 자료형을 사용하는 방향으로 리팩토링하는 것도 고려해보시면 좋을 거 같아요.

```java
    static public LocalDate startDate(int year, int month){
        return LocalDate.of(year, month, 1);
    }

    static public LocalDate getDate(int year, int month, int day){
        return LocalDate.of(year, month, day);
    }
```

2023-11-01 13:26 UTC, geniushyeon approved these changes

2023-11-01 13:27 UTC, merged