JWT 개발 완료
yeogiya/yeogiya-backend pull request #5
Opened 2023-07-21 02:25 UTC by ijnooyah

- 스프링 시큐리티 등과 함께 개발 완료

2023-07-21 14:19 UTC, geniushyeon requested changes
우선 일부만 리뷰해봤는데 확인 부탁드립니다!

2023-07-21 14:19 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/PasswordUtil.java
> +public class PasswordUtil {
이 클래스는 역할이 뭔가요!?

2023-07-21 14:19 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtService.java
> +                    .getClaim(ID_CLAIM) // claim(Emial) 가져오기
코드에는 `ID_CLAIM`이라고 되어있는데 이메일을 가져오는 건가요!?

2023-07-21 14:19 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtAuthenticationProcessingFilter.java
> +    private static final String NO_CHECK_URL = "/login"; // "/login"으로 들어오는 요청은 Filter 작동 X
회원가입 URL도 추가해야하지 않을까 싶네요~!

2023-07-21 14:19 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtAuthenticationProcessingFilter.java
> +                .ifPresent(accessToken -> jwtService.extractEmail(accessToken)
이메일인지 아이디인지 확실하게 한 다음 메소드명을 바꿔야 할 거 같네요

2023-07-21 14:19 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtAuthenticationProcessingFilter.java
> +    public void saveAuthentication(Member myMember) {
이 부분이 잘 이해가 안되는데.. 왜 소셜로그인 유저의 비밀번호를 임의로 설정하는 건가요? Spring Security랑 소셜로그인을 같이 사용하려면 필요한 절차인가요?

2023-07-21 14:19 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/PasswordUtil.java
> +        System.out.println(password);
이 sysout 코드는 빼고 반영하는 게 좋을 거 같습니다

2023-07-21 14:19 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtService.java
> +    public void setAccessTokenHeader(HttpServletResponse response, String accessToken) {
이 메소드처럼 같은 서비스 클래스 내부에서만 쓰는 메소드는 private으로 설정하는게 좋을 거 같습니다.

2023-07-22 01:32 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtService.java
> +                    .getClaim(ID_CLAIM) // claim(Emial) 가져오기
아니요아니요 아이디인데 수정을 못했네요

2023-07-22 01:34 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtAuthenticationProcessingFilter.java
> +    private static final String NO_CHECK_URL = "/login"; // "/login"으로 들어오는 요청은 Filter 작동 X
어디다 추가해야한다는 말씀이시죠?

2023-07-22 01:34 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtAuthenticationProcessingFilter.java
> +                .ifPresent(accessToken -> jwtService.extractEmail(accessToken)
넵!

2023-07-22 01:36 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtAuthenticationProcessingFilter.java
> +    public void saveAuthentication(Member myMember) {
제가 참고한 블로그에 여쭤봤습니다!

2023-07-23 14:39 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtAuthenticationProcessingFilter.java
> +    private static final String NO_CHECK_URL = "/login"; // "/login"으로 들어오는 요청은 Filter 작동 X
이 필터에서 JWT 인증이 필요한 API 요청이 들어왔을 때 토큰이 있는지 검사하는 거 아닌가요? 회원가입 API에도 토큰이 없을텐데 이 필터가 동작하지 않는게 맞지 않나 싶어요~

2023-07-25 05:56 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/jwt/JwtAuthenticationProcessingFilter.java
> +    private static final String NO_CHECK_URL = "/login"; // "/login"으로 들어오는 요청은 Filter 작동 X
오 맞네요... 그러면 회원가입url도 필요하겠군요 일단 원코드 주인분께 여쭤보고 말씀드릴게요

2023-07-27 04:37 UTC, geniushyeon approved these changes
우선 이대로 머지하고 나중에 다시 고치는게 좋을거같습니다

2023-07-27 04:37 UTC, merged