Feature/yb 20 sign up
yeogiya/yeogiya-backend pull request #8
Opened 2023-09-15 06:58 UTC by ijnooyah

2023-09-25 14:51 UTC, geniushyeon requested changes

2023-09-25 14:51 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/dto/MemberSignUpDto.java
> +public class MemberSignUpDto {
클래스 이름이 `Dto`랑 `DTO`가 혼용되고 있어서 통일하면 좋을 듯 합니다!

2023-09-25 14:51 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/controller/MemberController.java
> +    public String signUp(@Valid @RequestBody MemberSignUpDto memberSignUpDto) throws Exception {
이 API 리턴값은 String으로 두시는 건가요? 어떻게 하면 좋을지 생각해보시면 좋을 거 같습니다~

2023-09-25 14:51 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/service/MemberService.java
> +        if (memberRepository.findById(memberSignUpDto.getEmail()).isPresent()) {
클래스 내부에 중복체크하는 메소드가 있으니 그걸 활용하는 건 어떨까요?

2023-10-04 04:12 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/controller/MemberController.java
> +    public String signUp(@Valid @RequestBody MemberSignUpDto memberSignUpDto) throws Exception {
리턴값을 뭐라두기를 추천하시나요?

2023-10-04 04:13 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/service/MemberService.java
> +        if (memberRepository.findById(memberSignUpDto.getEmail()).isPresent()) {
어떤 메소드를 말하시는 거죠?

2023-10-04 09:13 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/service/MemberService.java
> +        if (memberRepository.findById(memberSignUpDto.getEmail()).isPresent()) {
checkDuplication 이요!

2023-10-04 09:14 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/controller/MemberController.java
> +    public String signUp(@Valid @RequestBody MemberSignUpDto memberSignUpDto) throws Exception {
회원가입을 완료했으니 회원가입된 사용자의 정보를 return해도 될 것 같고, 따로 body 없이 상태코드 200만 리턴해도 될 것 같아요!

2023-10-04 11:17 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/controller/MemberController.java
> +    public String signUp(@Valid @RequestBody MemberSignUpDto memberSignUpDto) throws Exception {
밑에 boolean값 리턴하는 메소드들 말하시는건가요???!! 여기에도 써도 괜찮은거죠?

2023-10-04 11:17 UTC, ijnooyah commented on yeogiya-web/src/main/java/com/yeogiya/web/service/MemberService.java
> +        if (memberRepository.findById(memberSignUpDto.getEmail()).isPresent()) {
밑에 boolean값 리턴하는 메소드들 말하시는건가요???!! 여기에도 써도 괜찮은거죠?

2023-10-04 11:55 UTC, geniushyeon commented on yeogiya-web/src/main/java/com/yeogiya/web/service/MemberService.java
> +        if (memberRepository.findById(memberSignUpDto.getEmail()).isPresent()) {
네네 맞습니다

2023-10-04 13:44 UTC, geniushyeon approved these changes

2023-10-04 13:45 UTC, merged